# permissions for end users to edit cloudos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudos-editor-role
rules:
- apiGroups:
  - cloudos.anselmes.com
  resources:
  - cloudos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudos.anselmes.com
  resources:
  - cloudos/status
  verbs:
  - get
